repos:
    - repo: https://github.com/hhatto/autopep8
      rev: 'v2.3.2'  # Use the sha / tag you want to point at
      hooks:
          - id: autopep8
            language: system
    -   repo: https://github.com/PyCQA/prospector
        rev: v1.17.3 # The version of Prospector to use, if not 'master' for latest
        hooks:
        -   id: prospector
            language: system

